{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xapp_core.serviceAccountName" . }}
  labels:
{{ include "xapp_core.labels" . | nindent 4 }}
{{- end -}}
