apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xapp_core.fullname" . }}-config
  labels:
    {{- include "xapp_core.labels" . | nindent 4 }}
data:
  xapp_configuration.py: |-
    configuration = {
        "metadata": {
            "name": "{{ .Release.Name }}",
            "configName": "",
            "namespace": "{{ .Release.Namespace }}"
        },
        "description": "{{ .Values.description }}",
        "last_modified": "14/08/2020 22:17:00",
        'config': {
            'REDIS_URL': '{{ tpl .Values.xappFrameworkConfig.redisUrl . }}',
            'REDIS_PORT': {{ .Values.xappFrameworkConfig.redisPort }},

            {{ range .Values.draxConfig }}
            {{ if eq .type "int" }}
            '{{ .name }}': {{ .value }},
            {{ else }}
            '{{ .name }}': '{{ tpl .value $ }}',
            {{ end }}
            {{ end }}

            {{ range .Values.xappConfig }}
            {{ if eq .type "int" }}
            '{{ .name }}': {{ .value }},
            {{ else }}
            '{{ .name }}': '{{ tpl .value $ }}',
            {{ end }}
            {{ end }}

        },
        "jsonSchemaOptions": {},
        "uiSchemaOptions": {}
    }
