apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xapp_core.fullname" . }}-config
  labels:
    {{- include "xapp_core.labels" . | nindent 4 }}
data:
  xapp_configuration.json: |-
    {
        "metadata": {
            "name": "{{ .Release.Name }}",
            "configName": "",
            "namespace": "{{ .Release.Namespace }}"
        },
        "description": "{{ .Values.description }}",
        "last_modified": "14/08/2020 22:17:00",
        "config": {
            {{ range .Values.draxConfig }}
            {{ if eq .type "string" }}
            "{{ .name }}": "{{ tpl .value $ }}",
            {{ else }}
            "{{ .name }}": {{ .value }},
            {{ end }}
            {{ end }}

            {{ range .Values.xappConfig }}
            {{ if eq .type "string" }}
            "{{ .name }}": "{{ tpl .value $ }}",
            {{ else }}
            "{{ .name }}": {{ .value }},
            {{ end }}
            {{ end }}

            "REDIS_URL": "{{ tpl .Values.xappFrameworkConfig.redisUrl . }}",
            "REDIS_PORT": {{ .Values.xappFrameworkConfig.redisPort }}
        },
        "jsonSchemaOptions": {},
        "uiSchemaOptions": {}
    }
