{{- if .Values.health.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-health
  labels:
    {{- include "redis.labels" . | nindent 4 }}
data:
  ping_readiness_local.sh: |-
    response=$(
      timeout -s $1 \
      redis-cli \
        ping
    )
    if [ "$response" != "PONG" ]; then
      echo "$response"
      exit 1
    fi
  ping_liveness_local.sh: |-
    response=$(
      timeout -s $1 \
      redis-cli \
        ping
    )
    if [ "$response" != "PONG" ] && [ "$response" != "LOADING Redis is loading the dataset in memory" ]; then
      echo "$response"
      exit 1
    fi
{{- end }}
