apiVersion: v1
kind: Service
metadata:
  name: {{ include "xapp-api.fullname" . }}
  labels:
    {{- include "xapp-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{ if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "xapp-api.selectorLabels" . | nindent 4 }}
