# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_defs/oranCommand.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto_defs/oranCommand.proto',
  package='OpenRANCommandsPB',
  syntax='proto2',
  serialized_pb=_b('\n\x1cproto_defs/oranCommand.proto\x12\x11OpenRANCommandsPB\"T\n\x19OpenRan_UeHandoverCommand\x12\x12\n\ntargetCell\x18\x02 \x02(\t\x12\x12\n\nsourceCell\x18\x03 \x02(\t\x12\x0f\n\x07ueRicId\x18\n \x02(\t\"%\n\x13OpenRAN_DataRequest\x12\x0e\n\x06\x63\x65llId\x18\x01 \x01(\t\")\n\x17OpenRAN_StopCellRequest\x12\x0e\n\x06\x63\x65llId\x18\x01 \x02(\t\"m\n\x1cOpenRAN_ConfigureORANrequest\x12\x19\n\x11\x61utomaticHandover\x18\x01 \x02(\x08\x12\x1b\n\x13publishMeasurements\x18\x02 \x02(\x08\x12\x15\n\rpublishUeData\x18\x03 \x02(\x08\"\xf2\x02\n\x16OpenRAN_commandMessage\x12:\n\x0bmessageType\x18\x01 \x02(\x0e\x32%.OpenRANCommandsPB.CommandMessageType\x12\x12\n\noriginator\x18\x02 \x02(\t\x12>\n\x08handover\x18\x03 \x01(\x0b\x32,.OpenRANCommandsPB.OpenRan_UeHandoverCommand\x12;\n\x0b\x64\x61tarequest\x18\x04 \x01(\x0b\x32&.OpenRANCommandsPB.OpenRAN_DataRequest\x12\x43\n\x0fstopcellrequest\x18\x05 \x01(\x0b\x32*.OpenRANCommandsPB.OpenRAN_StopCellRequest\x12\x46\n\rconfigrequest\x18\x06 \x01(\x0b\x32/.OpenRANCommandsPB.OpenRAN_ConfigureORANrequest*\x87\x01\n\x12\x43ommandMessageType\x12\x14\n\x10\x43OMMAND_HANDOVER\x10\x01\x12\x17\n\x13\x43OMMAND_DATAREQUEST\x10\x02\x12\x14\n\x10\x43OMMAND_STOPCELL\x10\x03\x12\x15\n\x11\x43OMMAND_CONFIGURE\x10\x04\x12\x15\n\x11\x43OMMAND_REBALANCE\x10\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_COMMANDMESSAGETYPE = _descriptor.EnumDescriptor(
  name='CommandMessageType',
  full_name='OpenRANCommandsPB.CommandMessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMMAND_HANDOVER', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMAND_DATAREQUEST', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMAND_STOPCELL', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMAND_CONFIGURE', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMAND_REBALANCE', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=704,
  serialized_end=839,
)
_sym_db.RegisterEnumDescriptor(_COMMANDMESSAGETYPE)

CommandMessageType = enum_type_wrapper.EnumTypeWrapper(_COMMANDMESSAGETYPE)
COMMAND_HANDOVER = 1
COMMAND_DATAREQUEST = 2
COMMAND_STOPCELL = 3
COMMAND_CONFIGURE = 4
COMMAND_REBALANCE = 5



_OPENRAN_UEHANDOVERCOMMAND = _descriptor.Descriptor(
  name='OpenRan_UeHandoverCommand',
  full_name='OpenRANCommandsPB.OpenRan_UeHandoverCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='targetCell', full_name='OpenRANCommandsPB.OpenRan_UeHandoverCommand.targetCell', index=0,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sourceCell', full_name='OpenRANCommandsPB.OpenRan_UeHandoverCommand.sourceCell', index=1,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ueRicId', full_name='OpenRANCommandsPB.OpenRan_UeHandoverCommand.ueRicId', index=2,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=135,
)


_OPENRAN_DATAREQUEST = _descriptor.Descriptor(
  name='OpenRAN_DataRequest',
  full_name='OpenRANCommandsPB.OpenRAN_DataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cellId', full_name='OpenRANCommandsPB.OpenRAN_DataRequest.cellId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=174,
)


_OPENRAN_STOPCELLREQUEST = _descriptor.Descriptor(
  name='OpenRAN_StopCellRequest',
  full_name='OpenRANCommandsPB.OpenRAN_StopCellRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cellId', full_name='OpenRANCommandsPB.OpenRAN_StopCellRequest.cellId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=217,
)


_OPENRAN_CONFIGUREORANREQUEST = _descriptor.Descriptor(
  name='OpenRAN_ConfigureORANrequest',
  full_name='OpenRANCommandsPB.OpenRAN_ConfigureORANrequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='automaticHandover', full_name='OpenRANCommandsPB.OpenRAN_ConfigureORANrequest.automaticHandover', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='publishMeasurements', full_name='OpenRANCommandsPB.OpenRAN_ConfigureORANrequest.publishMeasurements', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='publishUeData', full_name='OpenRANCommandsPB.OpenRAN_ConfigureORANrequest.publishUeData', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=328,
)


_OPENRAN_COMMANDMESSAGE = _descriptor.Descriptor(
  name='OpenRAN_commandMessage',
  full_name='OpenRANCommandsPB.OpenRAN_commandMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageType', full_name='OpenRANCommandsPB.OpenRAN_commandMessage.messageType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='originator', full_name='OpenRANCommandsPB.OpenRAN_commandMessage.originator', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='handover', full_name='OpenRANCommandsPB.OpenRAN_commandMessage.handover', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datarequest', full_name='OpenRANCommandsPB.OpenRAN_commandMessage.datarequest', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stopcellrequest', full_name='OpenRANCommandsPB.OpenRAN_commandMessage.stopcellrequest', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='configrequest', full_name='OpenRANCommandsPB.OpenRAN_commandMessage.configrequest', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=701,
)

_OPENRAN_COMMANDMESSAGE.fields_by_name['messageType'].enum_type = _COMMANDMESSAGETYPE
_OPENRAN_COMMANDMESSAGE.fields_by_name['handover'].message_type = _OPENRAN_UEHANDOVERCOMMAND
_OPENRAN_COMMANDMESSAGE.fields_by_name['datarequest'].message_type = _OPENRAN_DATAREQUEST
_OPENRAN_COMMANDMESSAGE.fields_by_name['stopcellrequest'].message_type = _OPENRAN_STOPCELLREQUEST
_OPENRAN_COMMANDMESSAGE.fields_by_name['configrequest'].message_type = _OPENRAN_CONFIGUREORANREQUEST
DESCRIPTOR.message_types_by_name['OpenRan_UeHandoverCommand'] = _OPENRAN_UEHANDOVERCOMMAND
DESCRIPTOR.message_types_by_name['OpenRAN_DataRequest'] = _OPENRAN_DATAREQUEST
DESCRIPTOR.message_types_by_name['OpenRAN_StopCellRequest'] = _OPENRAN_STOPCELLREQUEST
DESCRIPTOR.message_types_by_name['OpenRAN_ConfigureORANrequest'] = _OPENRAN_CONFIGUREORANREQUEST
DESCRIPTOR.message_types_by_name['OpenRAN_commandMessage'] = _OPENRAN_COMMANDMESSAGE
DESCRIPTOR.enum_types_by_name['CommandMessageType'] = _COMMANDMESSAGETYPE

OpenRan_UeHandoverCommand = _reflection.GeneratedProtocolMessageType('OpenRan_UeHandoverCommand', (_message.Message,), dict(
  DESCRIPTOR = _OPENRAN_UEHANDOVERCOMMAND,
  __module__ = 'proto_defs.oranCommand_pb2'
  # @@protoc_insertion_point(class_scope:OpenRANCommandsPB.OpenRan_UeHandoverCommand)
  ))
_sym_db.RegisterMessage(OpenRan_UeHandoverCommand)

OpenRAN_DataRequest = _reflection.GeneratedProtocolMessageType('OpenRAN_DataRequest', (_message.Message,), dict(
  DESCRIPTOR = _OPENRAN_DATAREQUEST,
  __module__ = 'proto_defs.oranCommand_pb2'
  # @@protoc_insertion_point(class_scope:OpenRANCommandsPB.OpenRAN_DataRequest)
  ))
_sym_db.RegisterMessage(OpenRAN_DataRequest)

OpenRAN_StopCellRequest = _reflection.GeneratedProtocolMessageType('OpenRAN_StopCellRequest', (_message.Message,), dict(
  DESCRIPTOR = _OPENRAN_STOPCELLREQUEST,
  __module__ = 'proto_defs.oranCommand_pb2'
  # @@protoc_insertion_point(class_scope:OpenRANCommandsPB.OpenRAN_StopCellRequest)
  ))
_sym_db.RegisterMessage(OpenRAN_StopCellRequest)

OpenRAN_ConfigureORANrequest = _reflection.GeneratedProtocolMessageType('OpenRAN_ConfigureORANrequest', (_message.Message,), dict(
  DESCRIPTOR = _OPENRAN_CONFIGUREORANREQUEST,
  __module__ = 'proto_defs.oranCommand_pb2'
  # @@protoc_insertion_point(class_scope:OpenRANCommandsPB.OpenRAN_ConfigureORANrequest)
  ))
_sym_db.RegisterMessage(OpenRAN_ConfigureORANrequest)

OpenRAN_commandMessage = _reflection.GeneratedProtocolMessageType('OpenRAN_commandMessage', (_message.Message,), dict(
  DESCRIPTOR = _OPENRAN_COMMANDMESSAGE,
  __module__ = 'proto_defs.oranCommand_pb2'
  # @@protoc_insertion_point(class_scope:OpenRANCommandsPB.OpenRAN_commandMessage)
  ))
_sym_db.RegisterMessage(OpenRAN_commandMessage)


# @@protoc_insertion_point(module_scope)
